version: '3.7'
services:
  database:
    image: postgres
    container_name: wallet-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=wallet
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=wallet
    volumes:
      - pdgata:/data/postgres
  api:
    build: .
    container_name: wallet
    ports:
      - 3333:3333
    volumes:
      - .:/wallet/api
      - /wallet/api/node_modules
    links:
      - database
    depends_on:
      - database

volumes:
  pdgata:
    driver: local
